FROM cnfldemos/cp-server-connect-datagen:0.5.0-6.2.0

RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.1.1
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-influxdb:1.2.1
